# Generated by Django 5.2.6 on 2025-10-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображения'),
        ),
    ]
